name: gamepad-event-handler
version: 0.1.0.0
github: "satosystems/gamepad-event-handler"
license: BSD3
author: "Satoshi Ogata"
maintainer: "satosystems@gmail.com"
copyright: "(c) 2022 Satoshi Ogata"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/satosystems/gamepad-event-handler#readme>

dependencies:
  - base >= 4.7 && < 5
  - sdl2
  - vector

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  gamepad-event-handler:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - gamepad-event-handler
